
import { Language } from './types';

// Supabase Configuration
export const SUPABASE_URL = 'https://xscdwdnjujpkczfhqrgu.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY2R3ZG5qdWpwa2N6Zmhxcmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzEwNjgsImV4cCI6MjA3NjkwNzA2OH0.xuVAkWA5y1oDW_jC52I8JJXF-ovU-5LIBsY9yXzy6cA';

/**
 * Model and Voice Defaults
 */
export const DEFAULT_LIVE_API_MODEL = 'gemini-2.5-flash-native-audio-preview-09-2025';
export const DEFAULT_VOICE = 'Zephyr';

export const AVAILABLE_VOICES = [
  'Zephyr', 'Puck', 'Charon', 'Luna', 'Nova', 'Kore', 'Fenrir', 'Leda', 'Orus',
  'Aoede', 'Callirrhoe', 'Autonoe', 'Enceladus', 'Iapetus', 'Umbriel', 'Algieba',
  'Despina', 'Erinome', 'Algenib', 'Rasalgethi', 'Laomedeia', 'Achernar',
  'Alnilam', 'Schedar', 'Gacrux', 'Pulcherrima', 'Achird', 'Zubenelgenubi',
  'Vindemiatrix', 'Sadachbia', 'Sadaltager', 'Sulafat'
];

/**
 * Mapping Aliases to Supported Gemini Base Voices
 * Since the API supports: Zephyr, Puck, Charon, Kore, Fenrir
 * We distribute the requested aliases to provide distinct vocal characteristics.
 */
export const GREEK_VOICES = [
  // Zephyr Group (Neutral/Balanced)
  { id: 'Zephyr', name: 'Zephyr (The Wind)' },
  { id: 'Zephyr', name: 'Luna (The Moon)' },
  { id: 'Zephyr', name: 'Nova (The Star)' },
  { id: 'Zephyr', name: 'Aoede (The Muse of Song)' },
  { id: 'Zephyr', name: 'Autonoe (The High-Minded)' },
  { id: 'Zephyr', name: 'Algieba (The Lion\'s Mane)' },
  { id: 'Zephyr', name: 'Achernar (The River\'s End)' },
  { id: 'Zephyr', name: 'Pulcherrima (The Fairest)' },
  { id: 'Zephyr', name: 'Sadaltager (The Merchant\'s Luck)' },

  // Kore Group (Female/Clear/Soft)
  { id: 'Kore', name: 'Kore (The Maiden)' },
  { id: 'Kore', name: 'Leda (The Queen)' },
  { id: 'Kore', name: 'Callirrhoe (Beautiful Flow)' },
  { id: 'Kore', name: 'Despina (The Mistress)' },
  { id: 'Kore', name: 'Erinome (The Virtuous)' },
  { id: 'Kore', name: 'Laomedeia (Leader of Folk)' },
  { id: 'Kore', name: 'Schedar (The Breast)' },
  { id: 'Kore', name: 'Gacrux (The Cross)' },
  { id: 'Kore', name: 'Vindemiatrix (The Grape-Gatherer)' },
  { id: 'Kore', name: 'Sadachbia (The Lucky Star)' },

  // Puck Group (Youthful/Energetic/Bright)
  { id: 'Puck', name: 'Puck (The Sprite)' },
  { id: 'Puck', name: 'Orus (The Visionary)' },
  { id: 'Puck', name: 'Enceladus (The Giant)' },
  { id: 'Puck', name: 'Algenib (The Side)' },
  { id: 'Puck', name: 'Alnilam (The String of Pearls)' },
  { id: 'Puck', name: 'Achird (The Eternal)' },

  // Charon Group (Deep/Steady/Mature)
  { id: 'Charon', name: 'Charon (The Ferryman)' },
  { id: 'Charon', name: 'Iapetus (The Piercer)' },
  { id: 'Charon', name: 'Umbriel (The Shadow)' },
  { id: 'Charon', name: 'Zubenelgenubi (The Southern Claw)' },

  // Fenrir Group (Authoritative/Deep/Gravelly)
  { id: 'Fenrir', name: 'Fenrir (The Wolf)' },
  { id: 'Fenrir', name: 'Sulafat (The Tortoise)' },
  { id: 'Fenrir', name: 'Rasalgethi (The Kneeler\'s Head)' },
];

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'it', name: 'Italian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'zh', name: 'Chinese (Mandarin, Standard)' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ar', name: 'Arabic (Modern Standard)' },
  { code: 'tr', name: 'Turkish' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'th', name: 'Thai' },
  { code: 'pl', name: 'Polish' },
  { code: 'nl', name: 'Dutch (Standard Netherlands)' },
  { code: 'sv', name: 'Swedish' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ms', name: 'Malay' },
  { code: 'fa', name: 'Persian (Farsi)' },
  { code: 'he', name: 'Hebrew' },
  { code: 'el', name: 'Greek' },
  { code: 'bn', name: 'Bengali' },
  { code: 'jv', name: 'Javanese' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'te', name: 'Telugu' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'ur', name: 'Urdu' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'my', name: 'Burmese' },
  { code: 'km', name: 'Khmer' },
  { code: 'ne', name: 'Nepali' },
  { code: 'lo', name: 'Lao' },
  { code: 'uz', name: 'Uzbek' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'si', name: 'Sinhala' },
  { code: 'hy', name: 'Armenian' },
  { code: 'ka', name: 'Georgian' },
  { code: 'zh-yue', name: 'Yue Chinese (Cantonese)' },
  { code: 'wuu', name: 'Wu Chinese (Shanghainese)' },
  { code: 'min', name: 'Min Chinese (Hokkien, Taiwanese)' },
  { code: 'hak', name: 'Hakka Chinese' },
  { code: 'zh-sw', name: 'Southwestern Mandarin (Sichuanese)' },
  { code: 'arz', name: 'Arabic (Egyptian Dialect)' },
  { code: 'apc', name: 'Arabic (Levantine Dialect)' },
  { code: 'ary', name: 'Arabic (Moroccan Dialect / Darija)' },
  { code: 'arq', name: 'Arabic (Algerian Dialect)' },
  { code: 'afb', name: 'Arabic (Gulf Dialect)' },
  { code: 'mt', name: 'Maltese (Semitic Language)' },
  { code: 'fr-be', name: 'French (Belgian)' },
  { code: 'fr-ch', name: 'French (Swiss)' },
  { code: 'fr-qc', name: 'French (Quebec / Canadian)' },
  { code: 'fr-ivc', name: 'Ivorian French' },
  { code: 'nl-be', name: 'Flemish (Belgian Dutch)' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'fy', name: 'West Frisian' },
  { code: 'li', name: 'Limburgish' },
  { code: 'nds', name: 'Dutch Low Saxon (Nedersaksisch)' },
  { code: 'zea', name: 'Zeelandic (Zeêuws)' },
  { code: 'nl-brb', name: 'Brabantian Dialect' },
  { code: 'nl-hol', name: 'Hollandic Dialect' },
  { code: 'tl', name: 'Filipino (Tagalog)' },
  { code: 'en-tl', name: 'Taglish (Tagalog-English Mix)' },
  { code: 'en-ceb', name: 'Bislish (Cebuano-English Mix)' },
  { code: 'ceb', name: 'Cebuano (Bisaya)' },
  { code: 'ilo', name: 'Ilocano' },
  { code: 'hil', name: 'Hiligaynon (Ilonggo)' },
  { code: 'war', name: 'Waray-Waray' },
  { code: 'pam', name: 'Kapampangan' },
  { code: 'pag', name: 'Pangasinan' },
  { code: 'bik', name: 'Bicolano (Central)' },
  { code: 'cbk', name: 'Chavacano (Spanish Creole)' },
  { code: 'mag', name: 'Maguindanaon' },
  { code: 'tsg', name: 'Tausug' },
  { code: 'mrw', name: 'Maranao' },
  { code: 'sur', name: 'Surigaonon' },
  { code: 'kya', name: 'Kinaray-a' },
  { code: 'akl', name: 'Aklanon' },
  { code: 'mas', name: 'Masbateño' },
  { code: 'ron', name: 'Romblomanon' },
  { code: 'sbl', name: 'Sambal' },
  { code: 'cm-fr', name: 'Cameroon French' },
  { code: 'cm-en', name: 'Cameroon English' },
  { code: 'cm-pid', name: 'Cameroonian Pidgin English (Kamtok)' },
  { code: 'cm-mix', name: 'Camfranglais (Youth Mix)' },
  { code: 'byv', name: 'Medumba' },
  { code: 'dua', name: 'Duala' },
  { code: 'ewo', name: 'Ewondo' },
  { code: 'bam', name: 'Bamum' },
  { code: 'ful', name: 'Fulfulde (Pulaar) - North' },
  { code: 'bul', name: 'Bulu' },
  { code: 'bbj', name: 'Ghomala\'' },
  { code: 'bas', name: 'Basaa' },
  { code: 'lmb', name: 'Limbum' },
  { code: 'baf', name: 'Bamileke-Fe’fe’' },
  { code: 'kff', name: 'Kom' },
  { code: 'nci', name: 'Nouchi (Ivory Coast Slang Mix)' },
  { code: 'bci', name: 'Baoulé' },
  { code: 'dyu', name: 'Dioula (Jula) - Lingua Franca' },
  { code: 'bet', name: 'Bété' },
  { code: 'sef', name: 'Senoufo (Cebaara)' },
  { code: 'any', name: 'Agni (Anyin)' },
  { code: 'dnj', name: 'Yacouba (Dan)' },
  { code: 'wec', name: 'Guéré (Wè)' },
  { code: 'did', name: 'Dida' },
  { code: 'abi', name: 'Abbey' },
  { code: 'ati', name: 'Attié' },
  { code: 'nzi', name: 'Nzima' },
  { code: 'kro', name: 'Krou' },
  { code: 'goa', name: 'Gouro' },
  { code: 'ebr', name: 'Ebrié' },
  { code: 'adj', name: 'Adioukrou' },
  { code: 'abr', name: 'Abron' },
  { code: 'sw', name: 'Swahili' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'ig', name: 'Igbo' },
  { code: 'zu', name: 'Zulu' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'am', name: 'Amharic' },
  { code: 'ha', name: 'Hausa' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ro', name: 'Romanian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'cs', name: 'Czech' },
  { code: 'sk', name: 'Slovak' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'hr', name: 'Croatian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'no', name: 'Norwegian (Bokmål)' },
  { code: 'nn', name: 'Norwegian (Nynorsk)' },
  { code: 'da', name: 'Danish' },
  { code: 'sn', name: 'Shona' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'wo', name: 'Wolof' },
  { code: 'qu', name: 'Quechua (South American Indigenous)' },
  { code: 'grn', name: 'Guaraní (Paraguay Indigenous)' },
  { code: 'ay', name: 'Aymara' },
  { code: 'is', name: 'Icelandic' },
  { code: 'ga', name: 'Irish (Gaelic)' },
  { code: 'et', name: 'Estonian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'sq', name: 'Albanian' },
  { code: 'bho', name: 'Bhojpuri' },
];

export const ORB_SIZE = 80;
export const POLLING_INTERVAL_MIN = 800;
export const POLLING_INTERVAL_MAX = 2000;
export const CHUNK_PUNCTUATION = /[.!?…]$/;
export const CHUNK_MIN_LENGTH = 40;
export const CHUNK_SILENCE_TIMEOUT = 800;
